name: Windows build

on: [push, pull_request]

jobs:
  mingw_build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-libidn2
          mingw-w64-ucrt-x86_64-libressl
          pkgconf
          automake
          autoconf
          make
          texinfo
    - name: Build
      run: |
        autoreconf -i
        ./configure --with-tls=libressl --with-libidn --prefix=/ --localedir=../share/locale
        make
        make install-strip DESTDIR=/d/a/msmtp/tmp
        cp `ldd src/msmtp | awk '/\/ucrt64/ {print $3}' | uniq` /d/a/msmtp/tmp/bin/
    - name: Upload release to GitHub
      if: github.ref_type == 'tag'
      shell: pwsh
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        7z a msmtp.zip D:\a\msmtp\tmp\*
        gh release create ${{ github.ref_name }} --generate-notes || echo "Release already exists!"
        gh release upload ${{ github.ref_name }} msmtp.zip
    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: msmtp-ucrt64
        path: D:\a\msmtp\tmp\

  msvc_build:
    runs-on: windows-latest
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
    - uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    - name: Build
      run: |
        vcpkg integrate install
        cd msvc && msbuild msmtp.vcxproj -t:rebuild -verbosity:minimal -property:Configuration=Release
    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: msmtp-msvc
        path: msvc\bin\Release
