name: Windows build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-libidn2
          mingw-w64-ucrt-x86_64-libressl
          pkgconf
          automake
          autoconf
          make
          texinfo
    - name: Build
      run: |
        autoreconf -i
        ./configure --with-tls=openssl --with-libidn --prefix=/ libssl_CFLAGS=-I/ucrt64/include/libressl "libssl_LIBS=-llibressl -L@prefix/lib -llibrecrypto" "CFLAGS=-Wno-incompatible-pointer-types -DNOCRYPT"
        make
        make install-strip DESTDIR=/d/a/msmtp/tmp
        cd /d/a/_temp/msys64/ucrt64/bin
        cp libiconv-2.dll libidn2-0.dll libintl-8.dll liblibrecrypto-46.dll liblibressl-48.dll libunistring-5.dll libwinpthread-1.dll /d/a/msmtp/tmp/bin/
    - name: Upload release to GitHub
      if: github.ref_type == 'tag'
      shell: pwsh
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        7z a msmtp.zip D:\a\msmtp\tmp\*
        gh release create ${{ github.ref_name }} --generate-notes || echo "Release already exists!"
        gh release upload ${{ github.ref_name }} msmtp.zip
    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: msmtp
        path: D:\a\msmtp\tmp\
